# Migrated from PostgreSQL to libSQL server configuration.
version: "3.8"

services:
  #  db:
  #    image: postgres:15-alpine
  #    volumes:
  #      - postgres_data:/var/lib/postgresql/data/
  #    environment:
  #      POSTGRES_USER: ${POSTGRES_USER:-postgres}
  #      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changethis}
  #      POSTGRES_DB: ${POSTGRES_DB:-app_db}
  #    ports:
  #      - "5432:5432"
  #    networks:
  #      - app-network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin} # Default credentials
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    networks:
      - app-network

  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    ports:
      - "8080:8080" # Default libSQL server port
    volumes:
      - libsql_data:/data
    environment:
      - LIBSQL_ADMIN_TOKEN=changeme # Change this in production
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app # Mount API source code
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL:-sqlite+libsql://db:8080}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT:-minio:9000}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}
      MINIO_BUCKET: ${MINIO_BUCKET:-therapy-media}
      MINIO_USE_SSL: ${MINIO_USE_SSL:-false}
    depends_on:
      # - db # Removed as PostgreSQL is no longer used
      - minio
    networks:
      - app-network
    # Add stdin_open and tty for API development if needed for debugging/interaction
    # stdin_open: true
    # tty: true

volumes:
  # postgres_data: # Removed as PostgreSQL is no longer used
  minio_data:
  libsql_data:

networks:
  app-network:
    driver: bridge
