"""Apply encryption to PHI fields

Revision ID: 681bb9dfa786
Revises: 719aff670f41
Create Date: 2025-05-05 01:01:10.282089

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String, Text
from api.core.encryption import EncryptedType


# revision identifiers, used by Alembic.
revision: str = "681bb9dfa786"
down_revision: Union[str, None] = "719aff670f41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "planexercises",
        "title",
        existing_type=sa.VARCHAR(length=255),
        type_=EncryptedType(),
        existing_nullable=False,
    )
    op.alter_column(
        "planexercises",
        "instructions",
        existing_type=sa.TEXT(),
        type_=EncryptedType(),
        existing_nullable=True,
    )
    op.alter_column(
        "therapyplans",
        "title",
        existing_type=sa.VARCHAR(length=255),
        type_=EncryptedType(),
        existing_nullable=False,
    )
    op.alter_column(
        "therapyplans",
        "description",
        existing_type=sa.TEXT(),
        type_=EncryptedType(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=EncryptedType(),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        type_=EncryptedType(),
        existing_nullable=False,
    )
    op.alter_column(
        "progress",
        "notes",
        existing_type=sa.TEXT(),
        type_=EncryptedType(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "progress",
        "notes",
        existing_type=EncryptedType(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=EncryptedType(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "name",
        existing_type=EncryptedType(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "therapyplans",
        "description",
        existing_type=EncryptedType(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "therapyplans",
        "title",
        existing_type=EncryptedType(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "planexercises",
        "instructions",
        existing_type=EncryptedType(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "planexercises",
        "title",
        existing_type=EncryptedType(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
